export const ENGLAND = "england"
export const WALES = "wales"
export const SCOTLAND = "scotland"

export const COUNTRIES = [ENGLAND, WALES, SCOTLAND];

export const CATEGORIES = [
  "woods",
  "watersports",
  "lakes",
  "forest",
  "AONB",
  "national_park",
  "wild swimming",
  "nature_reserve",
  "mountains",
]

export const COUNTIES_ENGLAND = [
    "Bedfordshire",
    "Berkshire",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    // "Cornwall",
    // "Cumbria",
    // "Derbyshire",
    // "Devon",
    // "Dorset",
    // "County Durham",
    // "East Riding of Yorkshire",
    // "East Sussex",
    // "Essex",
    // "Gloucestershire",
    // "Greater London",
    // "Greater Manchester",
    // "Hampshire",
    // "Herefordshire",
    // "Hertfordshire",
    // "Isle of Wight",
    // "Kent",
    // "Lancashire",
    // "Leicestershire",
    // "Lincolnshire",
    // "Merseyside",
    // "Norfolk",
    // "Northamptonshire",
    // "Northumberland",
    // "North Yorkshire",
    // "Nottinghamshire",
    // "Oxfordshire",
    // "Rutland",
    // "Shropshire",
    // "Somerset",
    // "South Yorkshire",
    // "Staffordshire",
    // "Suffolk",
    // "Surrey",
    // "Tyne and Wear",
    // "Warwickshire",
    // "West Midlands",
    // "West Sussex",
    // "West Yorkshire",
    // "Wiltshire",
    // "Worcestershire"
  ];

  
 export const COUNTIES_SCOTLAND = [
    "Aberdeenshire",
    "Angus",
    "Argyll and Bute",
    "Ayrshire",
    "City of Edinburgh",
    "Clackmannanshire",
    "Dumfries and Galloway",
    "Dundee City",
    "East Lothian",
    "Fife",
    "Glasgow City",
    "Highland",
    "Inverclyde",
    "Midlothian",
    "Moray",
    "North Ayrshire",
    "North Lanarkshire",
    "Orkney Islands",
    "Perth and Kinross",
    "Renfrewshire",
    "Scottish Borders",
    "Shetland Islands",
    "South Ayrshire",
    "South Lanarkshire",
    "Stirling",
    "West Dunbartonshire",
    "West Lothian"
  ];


  export const COUNTIES_WALES = [
    "Blaenau Gwent",
    "Bridgend",
    "Caerphilly",
    "Cardiff",
    "Carmarthenshire",
    "Ceredigion",
    "Conwy",
    "Denbighshire",
    "Flintshire",
    "Gwynedd",
    "Isle of Anglesey",
    "Merthyr Tydfil",
    "Monmouthshire",
    "Neath Port Talbot",
    "Newport",
    "Pembrokeshire",
    "Powys",
    "Rhondda Cynon Taf",
    "Swansea",
    "Torfaen",
    "Vale of Glamorgan",
    "Wrexham"
  ];
  